name: Deploy to gh pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          source-folder: docs
          git-user: $SOME_USERNAME
          git-password: ${{ secrets.ACCESS_TOKEN }}
          deployment-branch: gh-pages
